### ISSUE TITLE
Spider Error: https://www.webnames.ru/tld/catalog/ru

### ISSUE THREAD

**Issue by rsolovyeaws** [ecodomen/nsreg-watcher#299]
2024-05-04 13:13:19 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.webnames.ru/tld/catalog/ru> (referer: None)
Traceback (most recent call last):
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/utils/defer.py", line 279, in iter_errback
    yield next(it)
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/spidermiddlewares/referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/spidermiddlewares/urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/spidermiddlewares/depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "/home/ecodomen/ecodomen-dev/env/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ecodomen/ecodomen-dev/src/grabber/nsreg/spiders/nsreg_webnames.py", line 45, in parse
    price_reg = find_price(self.component.regex['price_reg'], price_reg)
  File "/home/ecodomen/ecodomen-dev/src/grabber/nsreg/base_site_spider.py", line 27, in find_price
    price = f'{float(price)}'
ValueError: could not convert string to float: '₽'

**Comment by ilyinss** [comment]
смотрите: у вас есть `REGEX_PATTERN = r"([0-9]+)[.,\s]?₽.*"`
Это просто паттерн, он ничего не чистит в строке. Паттерн хороший, может отделить число от других знаков. Это ок.
Ломается все вот тут:

```
def parse(self, response):
        price_reg = response.xpath(self.component.path['price_reg']).get()
        price_reg = find_price(self.component.regex['price_reg'], price_reg)
```
потому что внутрь строки 'price' у вас попадает значок рубля:
"ValueError: could not convert string to float: '₽'"

как идея, в файле base_site_spider.py изменить:

```
# Удаляем пробельные символы из строки
            price = re.sub(r'\s', '', price).sub(r'₽', '', price)
```
т.е. удалить еще и значок рубля (он у вас к числу приклеивается)


интересно, что вы, вроде, берете значение группы (1), но значок рубля отчего-то не ловится и все равно остается в строке.
Возможно, он в какой-то другой кодировке.
```
if m := re.match(re_pattern, price):
            price = m.group(1)
```
